# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Landmark' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Landmark
	# add the Firebase pod for Google Analytics
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'LandmarkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LandmarkUITests' do
    # Pods for testing
  end

end
